### ISSUE TITLE
Difference in conversion numbers for SCILS vs Timsconvert

### ISSUE THREAD

**Issue by rebekahdadey** [gtluu/timsconvert#56]
Hello:

I recently tested one of my MALDI samples with timconvert vs SCILS. I uploaded the results to metaspace. Interestingly, SCILS found 21 annotations and timsconvert found 11 annotations for the exact same input file. Is it known that timsconvert is more stringent that SCILS lab? 

![SCILS_vs_timsconvert(1)](https://github.com/gtluu/timsconvert/assets/57678280/4180fb2b-af17-46c3-b978-161d044d1b88)
![Screen Shot 2023-11-09 at 6 13 54 PM](https://github.com/gtluu/timsconvert/assets/57678280/278ac283-f840-4ca9-9fc0-5955557cbf34)

**Comment by gtluu** [comment]
Hi @rebekahdadey 

My guess is that the difference you are seeing is due to the fact that TIMSCONVERT exports the raw data directly, while the SCiLS imzML export functionality provides the option to export preprocessed data (i.e. using normalized intensity instead of raw intensity). For more information on the export function, you can refer to the SCiLS manual (Section 7.2.1 as of SCiLS 2024a). Additionally, depending on the instrument used, the import process into SCiLS may include baseline processing and binning which can affect the data and improve the annotation rate.

If you have more details or questions on the import/export settings that were used in SCiLS and/or conversion settings used in TIMSCONVERT, I'd be happy to discuss more online/offline.
